spring:
  profiles:
    active: local
  h2:
    console:
      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
  session:
    timeout: 86400

  datasource:
    url: jdbc:h2:mem:onlineShopping;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

server:
  servlet:
    session:
      cookie:
        max-age: 172800