spring:
  h2:
    console:
#      enabled: true

  data:
    web:
      pageable:
        one-indexed-parameters: true

  datasource:
    url: jdbc:h2:mem:onlineShopping;NON_KEYWORDS=USER
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    defer-datasource-initialization: true

jwt:
  jwt-key: "qIfnVcAmfv/0dsuiEivRMNuHaFzslJUamg0siNVjCAA="