### 쿠키 발급 요청

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "dompoo@gmail.com",
  "password": "1234"
}

### 인증 페이지 요청

GET http://localhost:8080/test
Content-Type: application/json
Cookie: SESSION=0cc4fdf0-63c9-4ca0-baf3-0a5de668e7ae