### 인증 페이지 요청

GET http://localhost:8080/test
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIn0.31w6C8BPdC3rqqy1W67_Pp5vhu2bibMTx25o_1QZdZU

### JWT 발급 요청

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "dompoo@gmail.com",
  "password": "1234"
}